### ISSUE TITLE
`format_name()` throws `TypeError` after trying to unpack a `None` for a matched spectrum

### ISSUE THREAD

**Issue by matterhorn103** [matterhorn103/mora_the_explorer#14]
Presumably has to do with the naming of the spectrum.

Log file shows:

```
2024-10-11 09:06:47,629 \\mora\nmr\300er\Oct10-2024\40
2024-10-11 09:06:47,640 Spectrum matches search query!
2024-10-11 09:06:47,640 Exception raised by check_nmr
Traceback (most recent call last):
  File "mora_the_explorer\explorer\worker.py", line 33, in run
  File "mora_the_explorer\explorer\checknmr.py", line 566, in check_nmr
  File "mora_the_explorer\explorer\checknmr.py", line 186, in format_name
TypeError: Value after * must be an iterable, not NoneType
```

**Comment by matterhorn103** [comment]
Fixed by 57fa53f0a270aea43abf7289130bf7289058137a
